### PR TITLE
Support table metadata

### PR DESCRIPTION
**Pull request by WhatAKitty**
With https://github.com/maddingo/mockjdbc/blob/master/src/main/java/no/maddin/mockjdbc/MockResultSetMetaData.java

### CODE REVIEW

**Comment by WhatAKitty** [comment]
Urgently need it, hope you will accepted.

**Comment by kaiwinter** [comment]
Seems like a reasonable addition, thanks for you contribution 😃 Will make a new release soon.

**Comment by WhatAKitty** [comment]
Thanks

**Comment by WhatAKitty** [comment]
The 1.3.0 version has not published yet on maven now ?

**Comment by kaiwinter** [comment]
It's on jcenter now. Maven central sync needs some time but should follow but I don't know when. I hope I don't have to send it to Maven central by my own :roll_eyes:

**Comment by kaiwinter** [comment]
http://search.maven.org/#artifactdetails%7Ccom.googlecode.dummyjdbc%7Cdummyjdbc%7C1.3.0%7Cjar

**Pull request merged**
